<?php

namespace App\Filament\SalePoint\Resources\SalesResource\Pages;

use App\Filament\SalePoint\Resources\SalesResource;
use Filament\Resources\Pages\CreateRecord;
use Filament\Actions\Action;
use Illuminate\Database\Eloquent\Model;

class CreateSales extends CreateRecord
{
    protected static string $resource = SalesResource::class;

//    protected function handleRecordCreation(array $data): Model
//    {
//        dd($data);
////        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
//    }
//

//    protected function mutateFormDataBeforeCreate(array $data): array
//    {
//        dd($data);
//        return  $data;
//    }


}
